### ISSUE TITLE
The Butcher Command doesn't work

### ISSUE THREAD

**Issue by ZaneDragonBorn** [Exopandora/WorldHandler#14]
When I try to use it it'll give an error

**Comment by Exopandora** [comment]
What versions are you using ?

**Comment by ZaneDragonBorn** [comment]
> What versions are you using ?

I'm using 1.12.2

**Comment by Exopandora** [comment]
Make sure you have selected at least one entity from the "Configure" menu in order to butcher them. Otherwise the button will be disabled. Also make sure you have the permission to use commands. If it says `Selector '@e[r=radius,type=entity]' found nothing` it actually works as intended because there is no mob in the specified radius for the given entity type. Note: The butcher (/kill) command executes for every selected entity type. Please describe your issue in more detail if it persists.
