### ISSUE TITLE
Integrate with LM

### ISSUE THREAD

**Issue by pkej** [Exopandora/WorldHandler#3]
I like how the block pos1 and pos2 works in WH (World Handler) which makes it easy in creative mode to create selections when in empty air.

I also like LM (Land Manager) which visualizes the claims, but it uses a standard wand type selection, which often aren't that good. An integration would be great ;)

BTW, is it possible to get pos1 and pos2 through CraftTweaker/zenscript?

**Comment by Exopandora** [comment]
Land Manager is only available for 1.12. My current policy is that only add features to the latest version of the game/mod. I would suggest that you create an issue over at LM to add such functionality because there is not much i can do about it other than expanding the capabilities of LM rather than WH.

Also i have never used CraftTweaker/zenscript but i suggest you could just execute the /wh <pos1|pos2> commands. If you have access to java classes you can get the positions from
```
exopandora.worldhandler.helper.BlockHelper#getPos1
exopandora.worldhandler.helper.BlockHelper#getPos2
```
